# Generated by Django 3.2.15 on 2022-10-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='work_contents',
            new_name='daily_description',
        ),
    ]
